# Picom oficial; Xrender funciona también en máquinas virtuales.
backend = "xrender";
vsync = true;
use-damage = true;
corner-radius = 10;
shadow = true;
shadow-radius = 15;
shadow-opacity = 0.5;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-exclude = ["window_type = 'dock'", "window_type = 'desktop'"];
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
detect-client-opacity = true;
log-level = "warn";